
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: builder
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    command: >
      sh -c "pnpm run dev"
      # sh -c "rm -rf generated && rm -rf prisma/migrations && pnpm run prisma:migrate:reset && pnpm run prisma:migrate && pnpm run prisma:generate && pnpm run dev"

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
      target: builder
    env_file:
      - ./worker/.env
    volumes:
      - ./worker:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    command: >
      sh -c "pnpm run dev"
  postgres:
    image: postgres:17
    restart: always
    env_file:
      - ./api/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redisdata:/var/lib/redis/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  redisdata:
